### ISSUE TITLE
minitest failing for desi 18.7

### ISSUE THREAD

**Issue by julianbautista** [sbailey/desitest#24]
@sbailey   
With desi env 18.7 I'm having the following error when running mpi_select_mock_targets from desitarget.

It seems like it's related to MWS_NEARBY objects in the config file. 

```
ERROR:mpi_select_mock_targets:176:<module>: Pixels [5308] failed after 5.4 minutes
ERROR:mpi_select_mock_targets:179:<module>: Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2630, in _extr
act_colnum
    colnum = self._colnames_lower.index(colstr.lower())
ValueError: 'radialvelocity' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.1/lib/python3.6/site-packages/desitarget-0.21.1-py3.
6.egg/EGG-INFO/scripts/mpi_select_mock_targets", line 170, in <module>
    healpixels=rankpix[i:i+n], no_spectra=args.no_spectra)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.1/lib/python3.6/site-packages/desitarget-0.21.1-py3.
6.egg/desitarget/mock/build.py", line 606, in targets_truth
    MakeMock=AllMakeMock[ii])
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.1/lib/python3.6/site-packages/desitarget-0.21.1-py3.
6.egg/desitarget/mock/build.py", line 174, in read_mock
    dust_dir=dust_dir, mock_density=mock_density)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.1/lib/python3.6/site-packages/desitarget-0.21.1-py3.
6.egg/desitarget/mock/mockmaker.py", line 3665, in read
    mock_density=mock_density)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desitarget/0.21.1/lib/python3.6/site-packages/desitarget-0.21.1-py3.
6.egg/desitarget/mock/mockmaker.py", line 1867, in readmock
    data = fitsio.read(mockfile, columns=cols, upper=True, ext=1, rows=cut)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 101, in read
    data = fits[item].read(**keys)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 1813, in read
    data = self.read_columns(columns, **keys)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 1995, in read_
columns
    colnums = self._extract_colnums(columns)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2607, in _extr
act_colnums
    colnums[i] = self._extract_colnum(columns[i])
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/site-packages/fitsio/fitslib.py", line 2632, in _extr
act_colnum
    raise ValueError(mess)
ValueError: column name 'RADIALVELOCITY' not found (case insensitive)

```

**Comment by moustakas** [comment]
Looks like you're using a "desitarget/master" configuration file but with the `18.7` software.  When using `18.7` you need to model your configuration file (e.g., the various paths to the mock catalogs) on what's in `desitarget/doc/mock_example/input.yaml`.

**Comment by julianbautista** [comment]
Let me clarify:

When running on 18.7 (desitarget 0.21.1) I use 
[this config file](https://github.com/desihub/desitarget/blob/0.21.1/doc/mock_example/input.yaml)
When running on master (desitarget 0.24.0.dev2465) I use
[this one](https://github.com/desihub/desitarget/blob/master/doc/mock_example/input.yaml)

With 18.7, the desitarget step fails with the error above.
With master, the desitarget step works fine. The minitest breaks in a later step (desisim/simexp.py)

**Comment by sbailey** [comment]
Thanks for the report @julianbautista.  Are you using the 18.7 tag of desitest in addition to using the 18.7 software release kernel?  It looks like you might be using the master copy of desitest which isn't compatible with the 18.7 software release.

desitest keeps its own copy of desitarget/doc/mock_example/input.yaml -> desitest/mini/select-mock-targets.yaml, and I verified that the copy in minitest tag 18.7 matches the copy in desitarget tag 0.21.1, which is the tag used for the 18.7 release.

Apologies for the integration mess.  I'm going to get back to fixing up master now...

**Comment by weaverba137** [comment]
I'm going to assume that this has been fixed.  If not, we can reopen.
