### ISSUE TITLE
KeyError in run_target_qa

### ISSUE THREAD

**Issue by weaverba137** [sbailey/desitest#8]
Here's another bitmask key error, but this time in `run_target_qa`.

```
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desitarget/master/bin/run_target_qa", line 33, in <module>
    make_qa_page(ns.src,qadir=ns.dest,mocks=ns.mocks,makeplots=makeplots,max_bin_area=max_bin_area,imaging_map_file=ns.weightmapfile)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desitarget/master/py/desitarget/QA.py", line 2595, in make_qa_page
    weight=weight)
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desitarget/master/py/desitarget/QA.py", line 2202, in mock_make_qa_plots
    wobjtype = np.where(targs["DESI_TARGET"] & desi_mask[objtype])[0]
  File "/global/common/software/desi/cori/desiconda/20180518-1.2.5-spec/code/desiutil/1.9.11/lib/python3.6/site-packages/desiutil-1.9.11-py3.6.egg/desiutil/bitmask.py", line 142, in __getitem__
    return self._bits[bitname]
KeyError: 'BGS_FAINT'
```

**Comment by moustakas** [comment]
This is more of. a @geordie666 issue...  Looks like `BGS_FAINT` is no longer in `desi_mask`...

```python
from desitarget.targetmask import desi_mask
desi_mask['BGS_FAINT']
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-5acb1b3b9c07> in <module>()
----> 1 desi_mask['BGS_FAINT']

~/repos/desihub/desiutil/py/desiutil/bitmask.py in __getitem__(self, bitname)
    140         """Return mask for individual bitname.
    141         """
--> 142         return self._bits[bitname]
    143 
    144     def bitnum(self, bitname):

KeyError: 'BGS_FAINT'
```

**Comment by moustakas** [comment]
I think I found the issue -- stand by.

**Comment by sbailey** [comment]
`BGS_FAINT` is in `bgs_mask`, not `desi_mask`, but it is still there.  It looks like the problem is in the QA code with the wrong combination of objtype and mask.  Hopefully John has a fix on this.

FYI I think @geordie666 is in Europe this week and may not be responding to github tickets with the usual frequency, or at least not the usual phase.

**Comment by moustakas** [comment]
OK, I want to do this right but it'll take me more than just a few minutes.  I propose you skip the targeting QA so you can continue to run `minitest` and I'll have a fix by this evening.

**Comment by weaverba137** [comment]
Right, skipping for now.

**Comment by weaverba137** [comment]
Latest minitest notebook works fine.
